<?php

class ApiDocService {

    public static function getEndpoints(): array {
        return [
            'auth' => [
                'name' => lang('api_doc_group_auth'),
                'icon' => 'ti ti-lock',
                'endpoints' => [
                    [
                        'method' => 'POST',
                        'path' => '/auth/login',
                        'summary' => lang('api_doc_summary_login_token'),
                        'auth' => false,
                        'level' => 'Public',
                        'scope' => 'public',
                        'params' => [
                            ['name' => 'email', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_email_or_username')],
                            ['name' => 'password', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('password')],
                        ],
                        'request_example' => ['email' => 'admin@xiuno.com', 'password' => '123456'],
                        'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['access_token' => 'abc...', 'refresh_token' => 'def...', 'expires_in' => 7200, 'user' => ['uid' => 1, 'username' => lang('api_doc_example_username')]]],
                        'errors' => [401 => lang('login_user_or_password_error'), 422 => lang('api_doc_param_validation_failed')],
                    ],
                    [
                        'method' => 'POST',
                        'path' => '/auth/register',
                        'summary' => lang('api_doc_summary_register_user'),
                        'auth' => false,
                        'level' => 'Public',
                        'scope' => 'public',
                        'params' => [
                            ['name' => 'email', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_email')],
                            ['name' => 'username', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('username')],
                            ['name' => 'password', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('password')],
                        ],
                        'request_example' => ['email' => 'test@example.com', 'username' => 'testuser', 'password' => '123456'],
                        'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['uid' => 2, 'access_token' => 'abc...', 'refresh_token' => 'def...', 'expires_in' => 7200]],
                        'errors' => [409 => lang('api_doc_email_or_username_exists'), 422 => lang('api_doc_param_validation_failed')],
                    ],
                    [
                        'method' => 'POST',
                        'path' => '/auth/refresh',
                        'summary' => lang('api_doc_summary_refresh_token'),
                        'auth' => false,
                        'level' => 'Public',
                        'scope' => 'public',
                        'params' => [
                            ['name' => 'refresh_token', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_refresh_token')],
                        ],
                        'request_example' => ['refresh_token' => 'def...'],
                        'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['access_token' => 'new_abc...', 'refresh_token' => 'new_def...', 'expires_in' => 7200]],
                        'errors' => [401 => lang('api_doc_invalid_refresh_token')],
                    ],
                    [
                        'method' => 'POST',
                        'path' => '/auth/logout',
                        'summary' => lang('api_doc_summary_logout'),
                        'auth' => true,
                        'level' => 'Authenticated',
                        'scope' => 'readwrite',
                        'params' => [
                            ['name' => 'refresh_token', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_refresh_token')],
                        ],
                        'request_example' => ['refresh_token' => 'def...'],
                        'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null],
                        'errors' => [401 => lang('api_doc_unauthorized')],
                    ],
                ],
            ],
            'user' => [
                'name' => lang('api_doc_group_user'),
                'icon' => 'ti ti-user',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/user', 'summary' => lang('api_doc_summary_user_list'), 'auth' => false, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 50, 'total_pages' => 3]]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/user/me', 'summary' => lang('api_doc_summary_current_user'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['uid' => 1, 'username' => lang('api_doc_example_username')]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'GET', 'path' => '/user/me/permissions', 'summary' => lang('api_doc_summary_user_permissions'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['permissions' => ['thread.create', 'post.create']]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'GET', 'path' => '/user/{uid}', 'summary' => lang('api_doc_summary_user_detail'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['uid' => 1, 'username' => lang('api_doc_example_username')]], 'errors' => [404 => lang('user_not_exists')]],
                    ['method' => 'PUT', 'path' => '/user/{uid}', 'summary' => lang('api_doc_summary_update_user'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'username', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('username')], ['name' => 'email', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_email')], ['name' => 'password', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('password_new')]], 'request_example' => ['username' => 'newname'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['uid' => 1, 'username' => 'newname']], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('user_not_exists')]],
                    ['method' => 'GET', 'path' => '/user/{uid}/threads', 'summary' => lang('api_doc_summary_user_threads'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 10, 'total_pages' => 1]]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/user/{uid}/posts', 'summary' => lang('api_doc_summary_user_posts'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 5, 'total_pages' => 1]]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/user/{uid}/favorites', 'summary' => lang('api_doc_summary_user_favorites'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 3, 'total_pages' => 1]]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'GET', 'path' => '/user', 'summary' => lang('api_doc_summary_batch_users'), 'auth' => false, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'ids', 'type' => 'string', 'in' => 'query', 'required' => true, 'desc' => lang('api_doc_user_id_list')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => [['uid' => 1, 'username' => lang('api_doc_example_username')], ['uid' => 2, 'username' => 'test']]], 'errors' => [422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/user/{uid}/following', 'summary' => lang('api_doc_summary_user_following'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 5, 'total_pages' => 1]]], 'errors' => [404 => lang('user_not_exists')]],
                    ['method' => 'GET', 'path' => '/user/{uid}/followers', 'summary' => lang('api_doc_summary_user_followers'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 8, 'total_pages' => 1]]], 'errors' => [404 => lang('user_not_exists')]],
                    ['method' => 'GET', 'path' => '/user/{uid}/ai-config', 'summary' => lang('api_doc_summary_user_ai_config'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['ai_provider' => 'openai', 'ai_endpoint' => 'https://api.openai.com', 'ai_model' => 'gpt-4']], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'PUT', 'path' => '/user/{uid}/ai-config', 'summary' => lang('api_doc_summary_update_user_ai_config'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'ai_provider', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_ai_provider')], ['name' => 'ai_apikey', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_ai_apikey')], ['name' => 'ai_endpoint', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_ai_endpoint')], ['name' => 'ai_model', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('ai_model_name')]], 'request_example' => ['ai_provider' => 'openai', 'ai_model' => 'gpt-4'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['ai_provider' => 'openai', 'ai_model' => 'gpt-4']], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'POST', 'path' => '/user/{uid}/avatar', 'summary' => lang('upload_avatar'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'file', 'type' => 'file', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_avatar_file')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['avatar_url' => 'upload/avatar/1.jpg']], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_file_type_not_allowed')]],
                    ['method' => 'POST', 'path' => '/user/{uid}/avatar/preset', 'summary' => lang('api_doc_summary_select_preset_avatar'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'avatar_index', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_avatar_index')]], 'request_example' => ['avatar_index' => 3], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['avatar_url' => 'upload/avatar/preset_3.png']], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/user/{uid}/avatar/presets', 'summary' => lang('api_doc_summary_preset_avatar_list'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['presets' => [['index' => 1, 'url' => 'upload/avatar/preset_1.png'], ['index' => 2, 'url' => 'upload/avatar/preset_2.png']]]], 'errors' => [404 => lang('user_not_exists')]],
                    ['method' => 'POST', 'path' => '/user/{uid}/follow', 'summary' => lang('api_doc_summary_follow_user'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_target_user_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['following' => true]], 'errors' => [401 => lang('api_doc_unauthorized'), 404 => lang('user_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/user/{uid}/follow', 'summary' => lang('api_doc_summary_unfollow_user'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_target_user_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['following' => false]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                ],
            ],
            'my' => [
                'name' => lang('my'),
                'icon' => 'ti ti-user-circle',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/my/profile', 'summary' => lang('api_doc_summary_my_profile'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['uid' => 1, 'username' => lang('api_doc_example_username'), 'email' => 'admin@xiuno.com']], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'PUT', 'path' => '/my/profile', 'summary' => lang('api_doc_summary_update_my_profile'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'username', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('username')], ['name' => 'signature', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('signature')]], 'request_example' => ['username' => 'newname'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['uid' => 1, 'username' => 'newname']], 'errors' => [401 => lang('api_doc_unauthorized'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'PUT', 'path' => '/my/password', 'summary' => lang('update_password'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'old_password', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_old_password')], ['name' => 'new_password', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('password_new')]], 'request_example' => ['old_password' => '***', 'new_password' => '***'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_old_password_wrong'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/my/email', 'summary' => lang('api_doc_summary_my_email'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['email' => 'admin@xiuno.com', 'verified' => true]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'PUT', 'path' => '/my/email', 'summary' => lang('modify_email'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'email', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('new_email')], ['name' => 'code', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('verify_code')]], 'request_example' => ['email' => 'new@example.com', 'code' => '123456'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['email' => 'new@example.com']], 'errors' => [401 => lang('api_doc_unauthorized'), 409 => lang('api_doc_email_exists'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'POST', 'path' => '/my/email/send-code', 'summary' => lang('api_doc_summary_send_email_code'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'email', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_target_email')]], 'request_example' => ['email' => 'new@example.com'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 422 => lang('api_doc_param_validation_failed'), 429 => lang('api_doc_send_too_frequent')]],
                    ['method' => 'GET', 'path' => '/my/security', 'summary' => lang('api_doc_summary_security_info'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['email_verified' => true, 'two_factor' => false, 'last_login' => 1719900000]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'GET', 'path' => '/my/credits/rules', 'summary' => lang('api_doc_summary_credits_rules'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['rules' => []]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'POST', 'path' => '/my/credits/check', 'summary' => lang('api_doc_summary_check_credits'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'type', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_credits_type')], ['name' => 'amount', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_amount')]], 'request_example' => ['amount' => 5], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['sufficient' => true, 'balance' => 100]], 'errors' => [401 => lang('api_doc_unauthorized'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/my/likes', 'summary' => lang('api_doc_summary_my_likes'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 0, 'total_pages' => 0]]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'GET', 'path' => '/my/feed', 'summary' => lang('api_doc_summary_my_feed'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 0, 'total_pages' => 0]]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'GET', 'path' => '/my/follow-users', 'summary' => lang('api_doc_summary_my_following'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 0, 'total_pages' => 0]]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'GET', 'path' => '/my/notify/dropdown', 'summary' => lang('api_doc_summary_notify_dropdown'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'unread' => 0]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                ],
            ],
            'thread' => [
                'name' => lang('thread'),
                'icon' => 'ti ti-message',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/thread', 'summary' => lang('thread_list'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'fid', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_forum_id_filter')], ['name' => 'uid', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_user_id_filter')], ['name' => 'keyword', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_keyword_search')], ['name' => 'orderby', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_orderby')], ['name' => 'order', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_order_direction')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 100, 'total_pages' => 5]]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/thread/{tid}', 'summary' => lang('thread_detail'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['tid' => 1, 'fid' => 1, 'subject' => lang('api_doc_example_subject')]], 'errors' => [404 => lang('thread_not_exists')]],
                    ['method' => 'POST', 'path' => '/thread', 'summary' => lang('api_doc_summary_create_thread'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'fid', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_forum_id')], ['name' => 'subject', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('subject')], ['name' => 'message', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('message')]], 'request_example' => ['fid' => 1, 'subject' => lang('api_doc_example_subject_test'), 'message' => lang('api_doc_example_message_content')], 'response_example' => ['code' => 0, 'msg' => 'Created', 'data' => ['tid' => 1]], 'errors' => [401 => lang('api_doc_unauthorized'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'PUT', 'path' => '/thread/{tid}', 'summary' => lang('api_doc_summary_update_thread'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')], ['name' => 'subject', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_new_subject')]], 'request_example' => ['subject' => lang('api_doc_example_subject_new')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['tid' => 1, 'subject' => lang('api_doc_example_subject_new')]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('thread_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/thread/{tid}', 'summary' => lang('delete_thread'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'Deleted', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('thread_not_exists')]],
                    ['method' => 'POST', 'path' => '/thread/{tid}/like', 'summary' => lang('like_action'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['liked' => true]], 'errors' => [401 => lang('api_doc_unauthorized'), 404 => lang('thread_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/thread/{tid}/like', 'summary' => lang('api_doc_summary_unlike'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['liked' => false]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'POST', 'path' => '/thread/{tid}/favorite', 'summary' => lang('favorite_action'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['favorited' => true]], 'errors' => [401 => lang('api_doc_unauthorized'), 404 => lang('thread_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/thread/{tid}/favorite', 'summary' => lang('api_doc_summary_unfavorite'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['favorited' => false]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'POST', 'path' => '/thread/{tid}/report', 'summary' => lang('api_doc_summary_report'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')], ['name' => 'reason', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_report_reason')]], 'request_example' => ['reason' => lang('api_doc_example_reason')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 404 => lang('thread_not_exists'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'DELETE', 'path' => '/thread/batch', 'summary' => lang('api_doc_summary_batch_delete_threads'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tids', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_ids')]], 'request_example' => ['tids' => [1, 2, 3]], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['deleted' => 3]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'PUT', 'path' => '/thread/batch', 'summary' => lang('api_doc_summary_batch_update_threads'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tids', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_ids')], ['name' => 'update', 'type' => 'object', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_update_fields')]], 'request_example' => ['tids' => [1, 2], 'update' => ['top' => 1]], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['updated' => 2]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/thread', 'summary' => lang('api_doc_summary_batch_threads'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'ids', 'type' => 'string', 'in' => 'query', 'required' => true, 'desc' => lang('api_doc_thread_id_list')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => [['tid' => 1, 'subject' => lang('api_doc_example_subject_1')], ['tid' => 2, 'subject' => lang('api_doc_example_subject_2')]]], 'errors' => [422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/thread/hot', 'summary' => lang('api_doc_summary_hot_threads'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'days', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_days_range_default7')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize_default10')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => []]], 'errors' => []],
                    ['method' => 'POST', 'path' => '/thread/{tid}/announcement', 'summary' => lang('api_doc_summary_set_announcement'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_thread_id')], ['name' => 'is_announcement', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_announcement_flag')], ['name' => 'announcement_order', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_sort_weight')]], 'request_example' => ['is_announcement' => 1, 'announcement_order' => 0], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['tid' => 1, 'is_announcement' => 1]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('thread_not_exists')]],
                ],
            ],
            'post' => [
                'name' => lang('reply'),
                'icon' => 'ti ti-message-reply',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/post', 'summary' => lang('post_list'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_thread_id')], ['name' => 'uid', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_user_id')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 50, 'total_pages' => 3]]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/post/{pid}', 'summary' => lang('api_doc_summary_post_detail'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'pid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_post_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['pid' => 1, 'tid' => 1, 'message' => lang('reply')]], 'errors' => [404 => lang('post_not_exists')]],
                    ['method' => 'POST', 'path' => '/post', 'summary' => lang('api_doc_summary_create_post'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tid', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_id')], ['name' => 'message', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_post_content')]], 'request_example' => ['tid' => 1, 'message' => lang('reply')], 'response_example' => ['code' => 0, 'msg' => 'Created', 'data' => ['pid' => 1]], 'errors' => [401 => lang('api_doc_unauthorized'), 404 => lang('thread_not_exists'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'PUT', 'path' => '/post/{pid}', 'summary' => lang('api_doc_summary_update_post'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'pid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_post_id')], ['name' => 'message', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_new_message')]], 'request_example' => ['message' => lang('api_doc_example_message_modified')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['pid' => 1, 'message' => lang('api_doc_example_message_modified')]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('post_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/post/{pid}', 'summary' => lang('api_doc_summary_delete_post'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'pid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_post_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'Deleted', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('post_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/post/batch', 'summary' => lang('api_doc_summary_batch_delete_posts'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'pids', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_post_ids')]], 'request_example' => ['pids' => [1, 2, 3]], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['deleted' => 3]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'POST', 'path' => '/post/{pid}/like', 'summary' => lang('api_doc_summary_like_post'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'pid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_post_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['liked' => true]], 'errors' => [401 => lang('api_doc_unauthorized'), 404 => lang('post_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/post/{pid}/like', 'summary' => lang('api_doc_summary_unlike_post'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'pid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_post_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['liked' => false]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                ],
            ],
            'forum' => [
                'name' => lang('forum'),
                'icon' => 'ti ti-layout-list',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/forum', 'summary' => lang('api_doc_summary_forum_list'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 5, 'total_pages' => 1]]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/forum/{fid}', 'summary' => lang('api_doc_summary_forum_detail'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'fid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_forum_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['fid' => 1, 'name' => lang('api_doc_example_forum_name')]], 'errors' => [404 => lang('forum_not_exists')]],
                    ['method' => 'GET', 'path' => '/forum/{fid}/threads', 'summary' => lang('api_doc_summary_forum_threads'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'fid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_forum_id')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'orderby', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_orderby')], ['name' => 'keyword', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_keyword_search')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 50, 'total_pages' => 3]]], 'errors' => [404 => lang('forum_not_exists')]],
                    ['method' => 'GET', 'path' => '/forum/tree', 'summary' => lang('api_doc_summary_forum_tree'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => [['fid' => 1, 'name' => lang('api_doc_example_forum_name'), 'children' => []]]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/forum', 'summary' => lang('api_doc_summary_batch_forums'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'ids', 'type' => 'string', 'in' => 'query', 'required' => true, 'desc' => lang('api_doc_forum_id_list')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => [['fid' => 1, 'name' => lang('api_doc_example_forum_name')], ['fid' => 2, 'name' => lang('api_doc_example_forum_name_tech')]]], 'errors' => [422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'POST', 'path' => '/forum/follow', 'summary' => lang('api_doc_summary_follow_forum'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'fid', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_forum_id')]], 'request_example' => ['fid' => 1], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['following' => true]], 'errors' => [401 => lang('api_doc_unauthorized'), 404 => lang('forum_not_exists')]],
                    ['method' => 'POST', 'path' => '/forum/unfollow', 'summary' => lang('api_doc_summary_unfollow_forum'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'fid', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_forum_id')]], 'request_example' => ['fid' => 1], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['following' => false]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                ],
            ],
            'attach' => [
                'name' => lang('attachment'),
                'icon' => 'ti ti-paperclip',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/attach/{aid}', 'summary' => lang('api_doc_summary_attach_detail'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'aid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_attach_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['aid' => 1, 'filename' => 'image.jpg']], 'errors' => [404 => lang('attach_not_exists')]],
                    ['method' => 'POST', 'path' => '/attach', 'summary' => lang('api_doc_summary_upload_attach'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'file', 'type' => 'file', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_attach_file')], ['name' => 'tid', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_thread_id')], ['name' => 'pid', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_post_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'Uploaded', 'data' => ['aid' => 1, 'url' => 'upload/attach/202605/image.jpg']], 'errors' => [401 => lang('api_doc_unauthorized'), 422 => lang('api_doc_file_type_not_allowed')]],
                    ['method' => 'DELETE', 'path' => '/attach/{aid}', 'summary' => lang('api_doc_summary_delete_attach'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'aid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_attach_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'Deleted', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('attach_not_exists')]],
                ],
            ],
            'notify' => [
                'name' => lang('notification'),
                'icon' => 'ti ti-bell',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/notify', 'summary' => lang('api_doc_summary_notify_list'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'type', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_notify_type')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 5, 'total_pages' => 1]]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'GET', 'path' => '/notify/unread', 'summary' => lang('api_doc_summary_unread_notify_count'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['count' => 3]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'PUT', 'path' => '/notify/{id}/read', 'summary' => lang('api_doc_summary_mark_read'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'id', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_notify_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'PUT', 'path' => '/notify/read-all', 'summary' => lang('api_doc_summary_mark_all_read'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'DELETE', 'path' => '/notify/{id}', 'summary' => lang('api_doc_summary_delete_notify'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'id', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_notify_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 404 => lang('api_doc_notify_not_exists')]],
                ],
            ],
            'search' => [
                'name' => lang('search'),
                'icon' => 'ti ti-search',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/search', 'summary' => lang('api_doc_summary_fulltext_search'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'q', 'type' => 'string', 'in' => 'query', 'required' => true, 'desc' => lang('api_doc_search_keyword_min2')], ['name' => 'type', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_search_type')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 10, 'total_pages' => 1]]], 'errors' => [422 => lang('api_doc_param_validation_failed')]],
                ],
            ],
            'site' => [
                'name' => lang('api_doc_group_site'),
                'icon' => 'ti ti-world',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/site', 'summary' => lang('api_doc_summary_site_info'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['name' => 'Xiuno BBS', 'api_version' => '1.0']], 'errors' => []],
                    ['method' => 'GET', 'path' => '/site/stats', 'summary' => lang('api_doc_summary_site_stats'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['threads' => 100, 'posts' => 500, 'users' => 50]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/site/health', 'summary' => lang('api_doc_summary_health_check'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['status' => 'ok', 'db' => true, 'cache' => true]], 'errors' => []],
                ],
            ],
            'mod' => [
                'name' => lang('api_doc_group_mod'),
                'icon' => 'ti ti-shield',
                'endpoints' => [
                    ['method' => 'POST', 'path' => '/mod/top', 'summary' => lang('api_doc_summary_top_untop'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tidarr', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_ids')], ['name' => 'top', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_top_level')]], 'request_example' => ['tidarr' => [1, 2], 'top' => 1], 'response_example' => ['code' => 0, 'message' => lang('set_completely'), 'redirect_url' => './'], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('insufficient_privilege')]],
                    ['method' => 'POST', 'path' => '/mod/close', 'summary' => lang('api_doc_summary_close_open_thread'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tidarr', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_ids')], ['name' => 'close', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_close_flag')]], 'request_example' => ['tidarr' => [1], 'close' => 1], 'response_example' => ['code' => 0, 'message' => lang('set_completely'), 'redirect_url' => './'], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('insufficient_privilege')]],
                    ['method' => 'POST', 'path' => '/mod/delete', 'summary' => lang('delete_thread'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tidarr', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_ids')]], 'request_example' => ['tidarr' => [1, 2]], 'response_example' => ['code' => 0, 'message' => lang('delete_completely'), 'redirect_url' => './'], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('insufficient_privilege')]],
                    ['method' => 'POST', 'path' => '/mod/move', 'summary' => lang('move_thread'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tidarr', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_ids')], ['name' => 'newfid', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_target_forum_id')]], 'request_example' => ['tidarr' => [1], 'newfid' => 2], 'response_example' => ['code' => 0, 'message' => lang('move_completely'), 'redirect_url' => './'], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('insufficient_privilege'), 404 => lang('forum_not_exists')]],
                    ['method' => 'POST', 'path' => '/mod/announcement', 'summary' => lang('api_doc_summary_set_announcement'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'tidarr', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_ids')], ['name' => 'is_announcement', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_announcement_flag')], ['name' => 'announcement_order', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_sort_weight')]], 'request_example' => ['tidarr' => [1], 'is_announcement' => 1, 'announcement_order' => 0], 'response_example' => ['code' => 0, 'message' => lang('set_completely'), 'redirect_url' => './'], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('insufficient_privilege')]],
                ],
            ],
            'credits' => [
                'name' => lang('credits_label'),
                'icon' => 'ti ti-coin',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/credits', 'summary' => lang('api_doc_summary_credits_balance'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'type', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_credits_type')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['credits' => 100, 'type' => 'default']], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'GET', 'path' => '/credits/log', 'summary' => lang('api_doc_summary_credits_log'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readonly', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'type', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_credits_type')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 10, 'total_pages' => 1]]], 'errors' => [401 => lang('api_doc_unauthorized')]],
                    ['method' => 'POST', 'path' => '/credits/add', 'summary' => lang('api_doc_summary_credits_add'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_user_id_default_current')], ['name' => 'type', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_credits_type')], ['name' => 'amount', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_credits_add_amount')], ['name' => 'reason', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_credits_add_reason')]], 'request_example' => ['amount' => 10, 'reason' => lang('api_doc_example_reason_checkin')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['credits' => 110]], 'errors' => [401 => lang('api_doc_unauthorized'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'POST', 'path' => '/credits/sub', 'summary' => lang('api_doc_summary_credits_sub'), 'auth' => true, 'level' => 'Authenticated', 'scope' => 'readwrite', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_user_id_default_current')], ['name' => 'type', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_credits_type')], ['name' => 'amount', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_credits_sub_amount')], ['name' => 'reason', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_credits_sub_reason')]], 'request_example' => ['amount' => 5, 'reason' => lang('api_doc_example_reason_download')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['credits' => 105]], 'errors' => [401 => lang('api_doc_unauthorized'), 422 => lang('api_doc_param_validation_failed'), 403 => lang('api_doc_insufficient_credits')]],
                ],
            ],
            'rank' => [
                'name' => lang('api_doc_group_rank'),
                'icon' => 'ti ti-trophy',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/rank', 'summary' => lang('api_doc_summary_rank_overview'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['hot_threads' => [], 'active_users' => []]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/rank/threads', 'summary' => lang('api_doc_summary_rank_threads'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'period', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_period_week_month_all')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'page_size', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 50, 'total_pages' => 3]]], 'errors' => []],
                    ['method' => 'GET', 'path' => '/rank/users', 'summary' => lang('api_doc_summary_rank_users'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'period', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_period')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'page_size', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'fields', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_fields_filter')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 30, 'total_pages' => 2]]], 'errors' => []],
                ],
            ],
            'captcha' => [
                'name' => lang('verify_code'),
                'icon' => 'ti ti-shield-check',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/captcha/{scene}', 'summary' => lang('api_doc_summary_generate_captcha'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'scene', 'type' => 'string', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_captcha_scene')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['captcha_key' => 'abc123', 'image' => 'data:image/png;base64,...']], 'errors' => [422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'POST', 'path' => '/captcha/{scene}/verify', 'summary' => lang('api_doc_summary_verify_captcha'), 'auth' => false, 'level' => 'Public', 'scope' => 'public', 'params' => [['name' => 'scene', 'type' => 'string', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_captcha_scene')], ['name' => 'captcha', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_captcha_content')]], 'request_example' => ['captcha' => 'a3x7'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['valid' => true]], 'errors' => [422 => lang('api_doc_param_validation_failed'), 400 => lang('api_doc_captcha_invalid_or_expired')]],
                ],
            ],
            'admin' => [
                'name' => lang('api_doc_group_admin'),
                'icon' => 'ti ti-settings',
                'endpoints' => [
                    ['method' => 'GET', 'path' => '/admin/security', 'summary' => lang('api_doc_summary_security_config'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['security_captcha_login' => true, 'security_captcha_register' => true, 'security_login_attempts' => 5]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'PUT', 'path' => '/admin/security', 'summary' => lang('api_doc_summary_update_security_config'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'security_captcha_login', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_captcha_login_switch')], ['name' => 'security_captcha_register', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_captcha_register_switch')], ['name' => 'security_login_attempts', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_login_attempts')]], 'request_example' => ['security_captcha_login' => 1, 'security_login_attempts' => 5], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/admin/security/captcha', 'summary' => lang('api_doc_summary_captcha_config'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['captcha_type' => 'image', 'captcha_length' => 4, 'captcha_expire' => 300]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'PUT', 'path' => '/admin/security/captcha', 'summary' => lang('api_doc_summary_update_captcha_config'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'captcha_type', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_captcha_type')], ['name' => 'captcha_length', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_captcha_length')], ['name' => 'captcha_expire', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_captcha_expire')]], 'request_example' => ['captcha_type' => 'image', 'captcha_length' => 4], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/admin/audit/pending', 'summary' => lang('api_doc_summary_audit_pending'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'type', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_audit_type')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 5, 'total_pages' => 1]]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'POST', 'path' => '/admin/audit/approve', 'summary' => lang('audit_approve'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'target_type', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_audit_target_type')], ['name' => 'target_id', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_target_id')]], 'request_example' => ['target_type' => 'thread', 'target_id' => 1], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('api_doc_target_not_exists')]],
                    ['method' => 'POST', 'path' => '/admin/audit/reject', 'summary' => lang('audit_reject'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'target_type', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_audit_target_type')], ['name' => 'target_id', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_target_id')], ['name' => 'reason', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_reject_reason')]], 'request_example' => ['target_type' => 'thread', 'target_id' => 1, 'reason' => lang('api_doc_example_reason_violation')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('api_doc_target_not_exists')]],
                    ['method' => 'POST', 'path' => '/admin/audit/batch-approve', 'summary' => lang('api_doc_summary_audit_batch_approve'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'target_type', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_audit_target_type')], ['name' => 'ids', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_target_ids')]], 'request_example' => ['target_type' => 'thread', 'ids' => [1, 2, 3]], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['approved' => 3]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'POST', 'path' => '/admin/audit/batch-reject', 'summary' => lang('api_doc_summary_audit_batch_reject'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'target_type', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_audit_target_type')], ['name' => 'ids', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_target_ids')], ['name' => 'reason', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_reject_reason')]], 'request_example' => ['target_type' => 'thread', 'ids' => [1, 2], 'reason' => lang('api_doc_example_reason_violation')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['rejected' => 2]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/admin/sensitive-words', 'summary' => lang('api_doc_summary_sensitive_words'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['words' => [lang('api_doc_example_sensitive_word_1'), lang('api_doc_example_sensitive_word_2')]]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'POST', 'path' => '/admin/sensitive-words', 'summary' => lang('api_doc_summary_add_sensitive_word'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'word', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_sensitive_word')]], 'request_example' => ['word' => lang('api_doc_example_sensitive_word')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'DELETE', 'path' => '/admin/sensitive-words', 'summary' => lang('api_doc_summary_clear_sensitive_words'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'POST', 'path' => '/admin/sensitive-words/import', 'summary' => lang('api_doc_summary_import_sensitive_words'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'words', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_sensitive_words')]], 'request_example' => ['words' => [lang('api_doc_example_word_1'), lang('api_doc_example_word_2'), lang('api_doc_example_word_3')]], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['imported' => 3]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'DELETE', 'path' => '/admin/sensitive-words/{word}', 'summary' => lang('api_doc_summary_delete_sensitive_word'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'word', 'type' => 'string', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_sensitive_word')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('api_doc_sensitive_word_not_exists')]],
                    ['method' => 'GET', 'path' => '/admin/log/credits', 'summary' => lang('api_doc_summary_admin_credits_log'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_user_id')], ['name' => 'type', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_credits_type')], ['name' => 'date_start', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_date_start')], ['name' => 'date_end', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_date_end')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 100, 'total_pages' => 5]]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'GET', 'path' => '/admin/log/login', 'summary' => lang('api_doc_summary_login_log'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_user_id')], ['name' => 'success', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_success_flag')], ['name' => 'date_start', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_date_start')], ['name' => 'date_end', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_date_end')], ['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 200, 'total_pages' => 10]]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'GET', 'path' => '/admin/user', 'summary' => lang('api_doc_summary_admin_user_list'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')], ['name' => 'keyword', 'type' => 'string', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_keyword_search')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 50, 'total_pages' => 3]]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'POST', 'path' => '/admin/user', 'summary' => lang('create_user'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'username', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('username')], ['name' => 'email', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_email')], ['name' => 'password', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('password')]], 'request_example' => ['username' => 'newuser', 'email' => 'new@example.com', 'password' => '123456'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['uid' => 10]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 409 => lang('api_doc_already_exists'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'PUT', 'path' => '/admin/user/{uid}', 'summary' => lang('api_doc_summary_admin_update_user'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'username', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('username')], ['name' => 'email', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_email')], ['name' => 'gid', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_group_id')]], 'request_example' => ['gid' => 1], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('user_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/admin/user/{uid}', 'summary' => lang('delete_user'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('user_not_exists')]],
                    ['method' => 'POST', 'path' => '/admin/user/{uid}/ban', 'summary' => lang('api_doc_summary_ban_user'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'reason', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_ban_reason')], ['name' => 'expire', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_ban_expire')]], 'request_example' => ['reason' => lang('api_doc_example_reason_short'), 'expire' => 0], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('user_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/admin/user/{uid}/ban', 'summary' => lang('api_doc_summary_unban_user'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('api_doc_user_not_banned')]],
                    ['method' => 'GET', 'path' => '/admin/forum', 'summary' => lang('api_doc_summary_admin_forum_list'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => []]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'POST', 'path' => '/admin/forum', 'summary' => lang('api_doc_summary_create_forum'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'name', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_forum_name')], ['name' => 'fup', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_parent_forum_id')], ['name' => 'description', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_description')]], 'request_example' => ['name' => lang('api_doc_example_forum_name_new')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['fid' => 10]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'PUT', 'path' => '/admin/forum/{fid}', 'summary' => lang('api_doc_summary_update_forum'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'fid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_forum_id')], ['name' => 'name', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_forum_name')], ['name' => 'description', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_description')]], 'request_example' => ['name' => lang('api_doc_example_forum_name_modified')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('forum_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/admin/forum/{fid}', 'summary' => lang('api_doc_summary_delete_forum'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'fid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_forum_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('forum_not_exists')]],
                    ['method' => 'PUT', 'path' => '/admin/thread/batch', 'summary' => lang('api_doc_summary_admin_batch_update_threads'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'tids', 'type' => 'array', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_thread_ids')], ['name' => 'update', 'type' => 'object', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_update_fields')]], 'request_example' => ['tids' => [1, 2], 'update' => ['top' => 1]], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['updated' => 2]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/admin/setting', 'summary' => lang('api_doc_summary_site_setting'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['sitename' => 'Xiuno BBS']], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'PUT', 'path' => '/admin/setting', 'summary' => lang('api_doc_summary_update_site_setting'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'sitename', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_sitename')]], 'request_example' => ['sitename' => lang('api_doc_example_sitename')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'GET', 'path' => '/admin/banned-ip', 'summary' => lang('api_doc_summary_banned_ip_list'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 0, 'total_pages' => 0]]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'POST', 'path' => '/admin/banned-ip', 'summary' => lang('api_doc_summary_ban_ip'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'ip', 'type' => 'string', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_ip_address')], ['name' => 'reason', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_ban_reason')], ['name' => 'expire', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_expire_ts')]], 'request_example' => ['ip' => '1.2.3.4'], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 422 => lang('api_doc_param_validation_failed')]],
                    ['method' => 'DELETE', 'path' => '/admin/banned-ip/{ip}', 'summary' => lang('api_doc_summary_unban_ip'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'ip', 'type' => 'string', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_ip_address')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('api_doc_ip_not_banned')]],
                    ['method' => 'GET', 'path' => '/admin/banned-user', 'summary' => lang('api_doc_summary_banned_user_list'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'page', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_page')], ['name' => 'pagesize', 'type' => 'int', 'in' => 'query', 'required' => false, 'desc' => lang('api_doc_pagesize')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => ['list' => [], 'pagination' => ['page' => 1, 'pagesize' => 20, 'total' => 0, 'total_pages' => 0]]], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden')]],
                    ['method' => 'POST', 'path' => '/admin/banned-user', 'summary' => lang('api_doc_summary_ban_user'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'body', 'required' => true, 'desc' => lang('api_doc_user_id')], ['name' => 'reason', 'type' => 'string', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_ban_reason')], ['name' => 'expire', 'type' => 'int', 'in' => 'body', 'required' => false, 'desc' => lang('api_doc_expire_ts')]], 'request_example' => ['uid' => 5, 'reason' => lang('api_doc_example_reason_short')], 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('user_not_exists')]],
                    ['method' => 'DELETE', 'path' => '/admin/banned-user/{uid}', 'summary' => lang('api_doc_summary_unban_user'), 'auth' => true, 'level' => 'Admin', 'scope' => 'admin', 'params' => [['name' => 'uid', 'type' => 'int', 'in' => 'path', 'required' => true, 'desc' => lang('api_doc_user_id')]], 'request_example' => null, 'response_example' => ['code' => 0, 'msg' => 'ok', 'data' => null], 'errors' => [401 => lang('api_doc_unauthorized'), 403 => lang('api_doc_forbidden'), 404 => lang('api_doc_user_not_banned')]],
                ],
            ],
        ];
    }

    public static function getOpenApiSpec(): array {
        $spec = [
            'openapi' => '3.0.0',
            'info' => [
                'title' => 'Xiuno BBS API',
                'version' => '1.0.0',
                'description' => lang('api_doc_openapi_description'),
            ],
            'servers' => [['url' => '/api/v1']],
            'paths' => [],
            'components' => [
                'securitySchemes' => [
                    'AppAuth' => ['type' => 'apiKey', 'in' => 'header', 'name' => 'X-App-Id', 'description' => lang('api_doc_app_auth_description')],
                    'BearerAuth' => ['type' => 'http', 'scheme' => 'bearer'],
                ],
                'schemas' => [
                    'Pagination' => ['type' => 'object', 'properties' => ['page' => ['type' => 'integer'], 'pagesize' => ['type' => 'integer'], 'total' => ['type' => 'integer'], 'total_pages' => ['type' => 'integer']]],
                    'ErrorResponse' => ['type' => 'object', 'properties' => ['code' => ['type' => 'integer'], 'msg' => ['type' => 'string'], 'data' => ['type' => 'object', 'nullable' => true]]],
                ],
            ],
        ];
        foreach (self::getEndpoints() as $group) {
            foreach ($group['endpoints'] as $ep) {
                $path = $ep['path'];
                $method = strtolower($ep['method']);
                if (!isset($spec['paths'][$path])) $spec['paths'][$path] = [];
                $operation = ['summary' => $ep['summary'], 'responses' => ['200' => ['description' => 'Success']]];
                if (!empty($ep['level'])) {
                    $operation['x-level'] = $ep['level'];
                }
                if ($ep['auth']) {
                    $operation['security'] = [['AppAuth' => [], 'BearerAuth' => []]];
                } else {
                    $operation['security'] = [['AppAuth' => []]];
                }
                if (!empty($ep['params'])) {
                    $operation['parameters'] = [];
                    foreach ($ep['params'] as $p) {
                        if ($p['in'] === 'path') $operation['parameters'][] = ['name' => $p['name'], 'in' => 'path', 'required' => true, 'schema' => ['type' => $p['type'] === 'int' ? 'integer' : 'string'], 'description' => $p['desc']];
                        elseif ($p['in'] === 'query') $operation['parameters'][] = ['name' => $p['name'], 'in' => 'query', 'required' => $p['required'], 'schema' => ['type' => $p['type'] === 'int' ? 'integer' : 'string'], 'description' => $p['desc']];
                    }
                }
                $spec['paths'][$path][$method] = $operation;
            }
        }
        return $spec;
    }

    public static function getErrorCodes(): array {
        return [
            ['code' => 0, 'desc' => lang('success_label')],
            ['code' => 401, 'desc' => lang('api_doc_error_401')],
            ['code' => 403, 'desc' => lang('api_doc_error_403')],
            ['code' => 404, 'desc' => lang('api_doc_error_404')],
            ['code' => 405, 'desc' => lang('api_doc_error_405')],
            ['code' => 409, 'desc' => lang('api_doc_error_409')],
            ['code' => 422, 'desc' => lang('api_doc_param_validation_failed')],
            ['code' => 429, 'desc' => lang('api_doc_error_429')],
            ['code' => 500, 'desc' => lang('error_internal_error')],
        ];
    }
}
